"""Seed data for the 10 nations + UN Peace Council."""
TEAMS = [
    {
        "nation_name": "NEXUS",
        "nation_code": "NEXUS",
        "team_type": "nation",
        "seat_cap": 10,
        "baseline_prosperity": 120,
        "baseline_security": 70,
        "baseline_influence": 80,
        "description": "Tech superpower with huge offense and economy but legacy infra risks.",
    },
    {
        "nation_name": "IRONVEIL",
        "nation_code": "IRON",
        "team_type": "nation",
        "seat_cap": 10,
        "baseline_prosperity": 90,
        "baseline_security": 80,
        "baseline_influence": 60,
        "description": "Authoritarian cyber state with strong APTs and propaganda machine.",
    },
    {
        "nation_name": "GHOSTNET",
        "nation_code": "GNET",
        "team_type": "nation",
        "seat_cap": 8,
        "baseline_prosperity": 85,
        "baseline_security": 75,
        "baseline_influence": 70,
        "description": "Cyber-first small nation: elite offensive teams, agile decision-making.",
    },
    {
        "nation_name": "CORALHAVEN",
        "nation_code": "CORAL",
        "team_type": "nation",
        "seat_cap": 10,
        "baseline_prosperity": 130,
        "baseline_security": 55,
        "baseline_influence": 65,
        "description": "Resource-rich newcomer with massive GDP but nascent cyber talent.",
    },
    {
        "nation_name": "FROSTBYTE",
        "nation_code": "FRST",
        "team_type": "nation",
        "seat_cap": 8,
        "baseline_prosperity": 95,
        "baseline_security": 90,
        "baseline_influence": 75,
        "description": "Nordic-style democracy with best-in-class defense and alliances.",
    },
    {
        "nation_name": "SHADOWMERE",
        "nation_code": "SHDW",
        "team_type": "nation",
        "seat_cap": 8,
        "baseline_prosperity": 70,
        "baseline_security": 60,
        "baseline_influence": 55,
        "description": "Rogue state embracing asymmetric warfare and unpredictability.",
    },
    {
        "nation_name": "DAWNSHIELD",
        "nation_code": "DAWN",
        "team_type": "nation",
        "seat_cap": 10,
        "baseline_prosperity": 100,
        "baseline_security": 85,
        "baseline_influence": 90,
        "description": "Humanitarian coalition with rapid IR teams and diplomatic reach.",
    },
    {
        "nation_name": "NEONHAVEN",
        "nation_code": "NEON",
        "team_type": "nation",
        "seat_cap": 10,
        "baseline_prosperity": 125,
        "baseline_security": 65,
        "baseline_influence": 70,
        "description": "Mega-city corporate state controlling global supply chains.",
    },
    {
        "nation_name": "SKYWARD UNION",
        "nation_code": "SKY",
        "team_type": "nation",
        "seat_cap": 8,
        "baseline_prosperity": 110,
        "baseline_security": 80,
        "baseline_influence": 85,
        "description": "Space/comms bloc with satellite dominance and ISR advantage.",
    },
    {
        "nation_name": "LOTUS SANCTUM",
        "nation_code": "LOTUS",
        "team_type": "nation",
        "seat_cap": 8,
        "baseline_prosperity": 90,
        "baseline_security": 95,
        "baseline_influence": 60,
        "description": "Neutral data haven with elite defense and anonymised infrastructure.",
    },
    {
        "nation_name": "UN PEACE COUNCIL",
        "nation_code": "UN",
        "team_type": "un",
        "seat_cap": 5,
        "baseline_prosperity": 100,
        "baseline_security": 100,
        "baseline_influence": 120,
        "description": "Mediator team issuing resolutions and stability bonuses.",
    },
]
