"""Seed data for the 10 nations + UN Peace Council."""
TEAMS = [
    {
        "nation_name": "United States",
        "nation_code": "US",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 120,
        "baseline_security": 70,
        "baseline_influence": 80,
        "description": "Tech superpower with huge offense and economy but legacy infra risks.",
    },
    {
        "nation_name": "Russia",
        "nation_code": "RU",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 90,
        "baseline_security": 80,
        "baseline_influence": 60,
        "description": "Authoritarian cyber state with strong APTs and propaganda machine.",
    },
    {
        "nation_name": "China",
        "nation_code": "CN",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 85,
        "baseline_security": 75,
        "baseline_influence": 70,
        "description": "Cyber-first power with elite offensive teams and strategic patience.",
    },
    {
        "nation_name": "Brazil",
        "nation_code": "BR",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 130,
        "baseline_security": 55,
        "baseline_influence": 65,
        "description": "Resource-rich emerging power with massive GDP but nascent cyber talent.",
    },
    {
        "nation_name": "Estonia",
        "nation_code": "EE",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 95,
        "baseline_security": 90,
        "baseline_influence": 75,
        "description": "Small digital-first democracy with best-in-class defense and NATO alliances.",
    },
    {
        "nation_name": "North Korea",
        "nation_code": "KP",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 70,
        "baseline_security": 60,
        "baseline_influence": 55,
        "description": "Rogue state embracing asymmetric cyber warfare and unpredictability.",
    },
    {
        "nation_name": "United Kingdom",
        "nation_code": "UK",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 100,
        "baseline_security": 85,
        "baseline_influence": 90,
        "description": "Intelligence powerhouse with GCHQ, rapid IR teams and diplomatic reach.",
    },
    {
        "nation_name": "Japan",
        "nation_code": "JP",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 125,
        "baseline_security": 65,
        "baseline_influence": 70,
        "description": "Technology hub controlling critical supply chains with growing cyber capability.",
    },
    {
        "nation_name": "India",
        "nation_code": "IN",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 110,
        "baseline_security": 80,
        "baseline_influence": 85,
        "description": "Space and comms power with satellite dominance and ISR advantage.",
    },
    {
        "nation_name": "Canada",
        "nation_code": "CA",
        "team_type": "nation",
        "seat_cap": 999,
        "baseline_prosperity": 105,
        "baseline_security": 75,
        "baseline_influence": 80,
        "description": "Five Eyes member with strong diplomatic networks and growing cyber defence capability.",
    },
    {
        "nation_name": "UN Security Council",
        "nation_code": "UN",
        "team_type": "un",
        "seat_cap": 999,
        "baseline_prosperity": 100,
        "baseline_security": 100,
        "baseline_influence": 120,
        "description": "Mediator body issuing resolutions and stability bonuses.",
    },
]
